# Conda environment 

name: pcmol2

# channels:
  # - conda-forge

dependencies:
  - python=3.10
  - pip
  - pip:
    - rdkit
    - torch
    - tqdm
    - wandb 
    - papyrus-structure-pipeline
    - pandas
    - matplotlib