# Conda environment 

name: pcmol
channels:
  - pytorch

dependencies:
  - python=3.10
  - wget
  - pip
  - ipykernel
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - pip:
    - rdkit
    - tqdm
    - wandb 
    - papyrus-structure-pipeline
    - pandas
    - matplotlib